# Generated by Django 3.1.3 on 2021-04-20 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 20, 10, 40, 45, 665855))),
                ('rating', models.IntegerField(verbose_name=((1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')))),
            ],
        ),
    ]
