# Generated by Django 3.1.3 on 2021-04-20 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.TextField(max_length=100)),
                ('comment', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 20, 11, 28, 58, 452818))),
                ('rating', models.IntegerField(verbose_name=((1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')))),
            ],
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
