# Generated by Django 3.1.1 on 2021-06-14 10:38

import PNWproject.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20210614_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(storage=PNWproject.storage_backends.MediaStorage(), upload_to=''),
        ),
    ]
